version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: nanobanana
    main: ./cmd/nanobanana
    binary: nanobanana
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/lyalindotcom/nano-banana-cli/internal/cli.Version={{.Version}}
      - -X github.com/lyalindotcom/nano-banana-cli/internal/cli.Commit={{.Commit}}
      - -X github.com/lyalindotcom/nano-banana-cli/internal/cli.BuildDate={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: lyalindotcom
    name: nano-banana-cli
  prerelease: auto
  draft: false
  name_template: "v{{.Version}}"
